# Generated by Django 5.1.2 on 2024-10-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='domain',
            field=models.CharField(default='Default Domain', max_length=200),
        ),
    ]
