# Generated by Django 5.1.2 on 2024-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_homepage_options_homepage_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
