# Generated by Django 5.1.2 on 2024-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_homepage_options_homepage_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=200)),
                ('name', models.CharField(default='Default Name', max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Puzzle',
                'verbose_name_plural': 'Puzzle',
            },
        ),
    ]
