# Generated by Django 5.1.2 on 2024-11-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_realword_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realword',
            name='meta_description',
            field=models.TextField(blank=True, max_length=135, null=True),
        ),
    ]
