# Generated by Django 5.1.2 on 2024-11-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_realword_meta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realword',
            name='meta_description',
        ),
    ]
