# Generated by Django 5.1.2 on 2024-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='realword',
            name='definition',
            field=models.TextField(default='Default Definition', max_length=1000, unique=True),
        ),
    ]
