# Generated by Django 5.1.2 on 2024-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0005_alter_realword_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='realword',
            name='transcription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
