# Generated by Django 5.1.2 on 2024-11-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_realword_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='realword',
            name='antonym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realword',
            name='example',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='realword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='realword',
            name='synonym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='puzzle.realword')),
            ],
        ),
    ]
