# Generated by Django 5.1.2 on 2024-11-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_realword_antonym_realword_example_realword_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realword',
            name='antonym',
        ),
        migrations.RemoveField(
            model_name='realword',
            name='example',
        ),
        migrations.RemoveField(
            model_name='realword',
            name='synonym',
        ),
    ]
