# Generated by Django 5.1.2 on 2024-11-05 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_remove_realword_antonym_remove_realword_example_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonyms', to='puzzle.realword')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='puzzle.realword')),
            ],
        ),
    ]
